# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 5, 1, 1)
        self.cmapPlasma_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.cmapPlasma_radioButton.setChecked(True)
        self.cmapPlasma_radioButton.setObjectName("cmapPlasma_radioButton")
        self.cmap_buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.cmap_buttonGroup.setObjectName("cmap_buttonGroup")
        self.cmap_buttonGroup.addButton(self.cmapPlasma_radioButton)
        self.gridLayout.addWidget(self.cmapPlasma_radioButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.cmap_label = QtWidgets.QLabel(self.centralwidget)
        self.cmap_label.setObjectName("cmap_label")
        self.gridLayout.addWidget(self.cmap_label, 0, 0, 1, 1)
        self.slice_label = QtWidgets.QLabel(self.centralwidget)
        self.slice_label.setObjectName("slice_label")
        self.gridLayout.addWidget(self.slice_label, 0, 9, 1, 1)
        self.cmapViridis_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.cmapViridis_radioButton.setObjectName("cmapViridis_radioButton")
        self.cmap_buttonGroup.addButton(self.cmapViridis_radioButton)
        self.gridLayout.addWidget(self.cmapViridis_radioButton, 0, 2, 1, 1)
        self.cmapGray_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.cmapGray_radioButton.setObjectName("cmapGray_radioButton")
        self.cmap_buttonGroup.addButton(self.cmapGray_radioButton)
        self.gridLayout.addWidget(self.cmapGray_radioButton, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 10, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget_left = MplWidget(self.centralwidget)
        self.mplwidget_left.setMouseTracking(False)
        self.mplwidget_left.setObjectName("mplwidget_left")
        self.horizontalLayout.addWidget(self.mplwidget_left)
        self.mplwidget_right = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_right.sizePolicy().hasHeightForWidth())
        self.mplwidget_right.setSizePolicy(sizePolicy)
        self.mplwidget_right.setObjectName("mplwidget_right")
        self.horizontalLayout.addWidget(self.mplwidget_right)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.menuMain.addAction(self.actionOpen)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmapPlasma_radioButton.setText(_translate("MainWindow", "Plasma"))
        self.cmap_label.setText(_translate("MainWindow", "Choose a colormap:"))
        self.slice_label.setText(_translate("MainWindow", "Slice -/-"))
        self.cmapViridis_radioButton.setText(_translate("MainWindow", "Viridis"))
        self.cmapGray_radioButton.setText(_translate("MainWindow", "Gray"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionTest.setText(_translate("MainWindow", "test"))

from mplwidget import MplWidget
