# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget = MplWidget(self.centralwidget)
        self.mplwidget.setMouseTracking(False)
        self.mplwidget.setObjectName("mplwidget")
        self.horizontalLayout.addWidget(self.mplwidget)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 9)
        self.comboBox_magn_phase = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_magn_phase.setObjectName("comboBox_magn_phase")
        self.comboBox_magn_phase.addItem("")
        self.comboBox_magn_phase.addItem("")
        self.gridLayout.addWidget(self.comboBox_magn_phase, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(125, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(204, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 8, 1, 1)
        self.slice_label = QtWidgets.QLabel(self.centralwidget)
        self.slice_label.setObjectName("slice_label")
        self.gridLayout.addWidget(self.slice_label, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(37, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 698, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        self.menuColormap = QtWidgets.QMenu(self.menuBar)
        self.menuColormap.setObjectName("menuColormap")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.groupColormap = QtWidgets.QActionGroup(MainWindow)
        self.groupColormap.setObjectName("groupColormap")
        self.actionPlasma = QtWidgets.QAction(self.groupColormap)
        self.actionPlasma.setCheckable(True)
        self.actionPlasma.setChecked(True)
        self.actionPlasma.setObjectName("actionPlasma")
        self.actionViridis = QtWidgets.QAction(self.groupColormap)
        self.actionViridis.setCheckable(True)
        self.actionViridis.setObjectName("actionViridis")
        self.actionGray = QtWidgets.QAction(self.groupColormap)
        self.actionGray.setCheckable(True)
        self.actionGray.setObjectName("actionGray")
        self.menuMain.addAction(self.actionOpen)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionQuit)
        self.menuColormap.addAction(self.actionPlasma)
        self.menuColormap.addAction(self.actionViridis)
        self.menuColormap.addAction(self.actionGray)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuColormap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Show:"))
        self.comboBox_magn_phase.setItemText(0, _translate("MainWindow", "Magnitude", "magnitude"))
        self.comboBox_magn_phase.setItemText(1, _translate("MainWindow", "Phase", "phase"))
        self.slice_label.setText(_translate("MainWindow", "Slice -/-"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuColormap.setTitle(_translate("MainWindow", "Colormap"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionTest.setText(_translate("MainWindow", "test"))
        self.actionPlasma.setText(_translate("MainWindow", "Plasma"))
        self.actionViridis.setText(_translate("MainWindow", "Viridis"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))

from imageviewer.ui.mplwidget import MplWidget
