# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_name = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.label_name_value = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name_value.sizePolicy().hasHeightForWidth())
        self.label_name_value.setSizePolicy(sizePolicy)
        self.label_name_value.setMinimumSize(QtCore.QSize(80, 0))
        self.label_name_value.setObjectName("label_name_value")
        self.label_age = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_age.sizePolicy().hasHeightForWidth())
        self.label_age.setSizePolicy(sizePolicy)
        self.label_age.setObjectName("label_age")
        self.label_age_value = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_age_value.sizePolicy().hasHeightForWidth())
        self.label_age_value.setSizePolicy(sizePolicy)
        self.label_age_value.setMinimumSize(QtCore.QSize(50, 0))
        self.label_age_value.setObjectName("label_age_value")
        self.label_sex = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sex.sizePolicy().hasHeightForWidth())
        self.label_sex.setSizePolicy(sizePolicy)
        self.label_sex.setObjectName("label_sex")
        self.label_sex_value = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sex_value.sizePolicy().hasHeightForWidth())
        self.label_sex_value.setSizePolicy(sizePolicy)
        self.label_sex_value.setMinimumSize(QtCore.QSize(50, 0))
        self.label_sex_value.setObjectName("label_sex_value")
        self.label_date = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setObjectName("label_date")
        self.label_date_value = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_value.sizePolicy().hasHeightForWidth())
        self.label_date_value.setSizePolicy(sizePolicy)
        self.label_date_value.setMinimumSize(QtCore.QSize(60, 0))
        self.label_date_value.setObjectName("label_date_value")
        self.label_slice = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slice.sizePolicy().hasHeightForWidth())
        self.label_slice.setSizePolicy(sizePolicy)
        self.label_slice.setMinimumSize(QtCore.QSize(80, 0))
        self.label_slice.setObjectName("label_slice")
        self.label_show = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_show.sizePolicy().hasHeightForWidth())
        self.label_show.setSizePolicy(sizePolicy)
        self.label_show.setObjectName("label_show")
        self.comboBox_magn_phase = QtWidgets.QComboBox(self.splitter)
        self.comboBox_magn_phase.setObjectName("comboBox_magn_phase")
        self.comboBox_magn_phase.addItem("")
        self.comboBox_magn_phase.addItem("")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_statistics = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_statistics.sizePolicy().hasHeightForWidth())
        self.splitter_statistics.setSizePolicy(sizePolicy)
        self.splitter_statistics.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_statistics.setObjectName("splitter_statistics")
        self.label_roi_statistics = QtWidgets.QLabel(self.splitter_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roi_statistics.sizePolicy().hasHeightForWidth())
        self.label_roi_statistics.setSizePolicy(sizePolicy)
        self.label_roi_statistics.setMinimumSize(QtCore.QSize(110, 0))
        self.label_roi_statistics.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_roi_statistics.setFont(font)
        self.label_roi_statistics.setObjectName("label_roi_statistics")
        self.label_mean = QtWidgets.QLabel(self.splitter_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mean.sizePolicy().hasHeightForWidth())
        self.label_mean.setSizePolicy(sizePolicy)
        self.label_mean.setMinimumSize(QtCore.QSize(0, 0))
        self.label_mean.setObjectName("label_mean")
        self.label_mean_value = QtWidgets.QLabel(self.splitter_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mean_value.sizePolicy().hasHeightForWidth())
        self.label_mean_value.setSizePolicy(sizePolicy)
        self.label_mean_value.setMinimumSize(QtCore.QSize(0, 0))
        self.label_mean_value.setObjectName("label_mean_value")
        self.label_std = QtWidgets.QLabel(self.splitter_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_std.sizePolicy().hasHeightForWidth())
        self.label_std.setSizePolicy(sizePolicy)
        self.label_std.setObjectName("label_std")
        self.label_std_value = QtWidgets.QLabel(self.splitter_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_std_value.sizePolicy().hasHeightForWidth())
        self.label_std_value.setSizePolicy(sizePolicy)
        self.label_std_value.setObjectName("label_std_value")
        self.verticalLayout.addWidget(self.splitter_statistics)
        self.mplwidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        self.mplwidget.setMouseTracking(False)
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout.addWidget(self.mplwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 713, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        self.menuColormap = QtWidgets.QMenu(self.menuBar)
        self.menuColormap.setObjectName("menuColormap")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_h5 = QtWidgets.QAction(MainWindow)
        self.actionOpen_h5.setObjectName("actionOpen_h5")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionOpen_dcm = QtWidgets.QAction(MainWindow)
        self.actionOpen_dcm.setObjectName("actionOpen_dcm")
        self.groupColormap = QtWidgets.QActionGroup(MainWindow)
        self.groupColormap.setObjectName("groupColormap")
        self.actionPlasma = QtWidgets.QAction(self.groupColormap)
        self.actionPlasma.setCheckable(True)
        self.actionPlasma.setChecked(True)
        self.actionPlasma.setObjectName("actionPlasma")
        self.actionViridis = QtWidgets.QAction(self.groupColormap)
        self.actionViridis.setCheckable(True)
        self.actionViridis.setObjectName("actionViridis")
        self.actionGray = QtWidgets.QAction(self.groupColormap)
        self.actionGray.setCheckable(True)
        self.actionGray.setObjectName("actionGray")
        self.menuMain.addAction(self.actionOpen_h5)
        self.menuMain.addAction(self.actionOpen_dcm)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionQuit)
        self.menuColormap.addAction(self.actionPlasma)
        self.menuColormap.addAction(self.actionViridis)
        self.menuColormap.addAction(self.actionGray)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuColormap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_name_value.setText(_translate("MainWindow", "-"))
        self.label_age.setText(_translate("MainWindow", "Age:"))
        self.label_age_value.setText(_translate("MainWindow", "-"))
        self.label_sex.setText(_translate("MainWindow", "Sex:"))
        self.label_sex_value.setText(_translate("MainWindow", "-"))
        self.label_date.setText(_translate("MainWindow", "Date:"))
        self.label_date_value.setText(_translate("MainWindow", "----/--/--"))
        self.label_slice.setText(_translate("MainWindow", "Slice: -/-"))
        self.label_show.setText(_translate("MainWindow", "Show:"))
        self.comboBox_magn_phase.setItemText(0, _translate("MainWindow", "Magnitude", "magnitude"))
        self.comboBox_magn_phase.setItemText(1, _translate("MainWindow", "Phase", "phase"))
        self.label_roi_statistics.setText(_translate("MainWindow", "ROI statistics:"))
        self.label_mean.setText(_translate("MainWindow", "Mean:"))
        self.label_mean_value.setText(_translate("MainWindow", "-"))
        self.label_std.setText(_translate("MainWindow", "STD:"))
        self.label_std_value.setText(_translate("MainWindow", "-"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuColormap.setTitle(_translate("MainWindow", "Colormap"))
        self.actionOpen_h5.setText(_translate("MainWindow", "Open .h5 File"))
        self.actionOpen_h5.setToolTip(_translate("MainWindow", "Lets you select a .h5 file."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionTest.setText(_translate("MainWindow", "test"))
        self.actionOpen_dcm.setText(_translate("MainWindow", "Open DICOM"))
        self.actionOpen_dcm.setToolTip(_translate("MainWindow", "Lets you select a folder with DCM files."))
        self.actionPlasma.setText(_translate("MainWindow", "Plasma"))
        self.actionViridis.setText(_translate("MainWindow", "Viridis"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))

from imageviewer.ui.mplwidget import MplWidget
